version: 0.1

phases:
  build:
    commands:
      - echo Build started on `date`
      - npm install
      - aws cloudformation package --template-file NewSamTemplate.yaml --s3-bucket taco-alexa
                                   --output-template-file NewSamTemplate.yaml
  post_build:
    commands:
      - echo Running post_build commands
      - mkdir build-output
      - ls
      - cp -R index.js  build-output
      - cp -R node_modules build-output
      - ls build-output
      - cd build-output && zip -r ../build-output.zip ./*
      - ls
      - echo Build completed on `date`
artifacts:
  type: zip
  files:
    - build-output.zip
    - NewsamTemplate.yaml


