version: 0.1

phases:
  build:
    commands:
      - echo Build started on `date`
      - npm install
  post_build:
    commands:
      - echo Running post_build commands
      - echo Build completed on `date`
artifacts:
  files:
    - node_modules
    - index.js


